<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('procurement_upazilas', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->timestamps();
        });

        $upazilas = [
            'Abhaynagar Upazila',
            'Adamdighi Upazila',
            'Adarsh Sadar Upazila',
            'Aditmari Upazila',
            'Agailjhara Upazila',
            'Ajmiriganj Upazila',
            'Akhaura Upazila',
            'Akkelpur Upazila',
            'Alamdanga Upazila',
            'Alfadanga Upazila',
            'Alikadam Upazila',
            'Amtali Upazila',
            'Anwara Upazila',
            'Araihazar Upazila',
            'Asashuni Upazila',
            'Ashtagram Upazila',
            'Ashuganj Upazila',
            'Atgharia Upazila',
            'Atpara Upazila',
            'Atrai Upazila',
            'Atwari Upazila',
            'Babuganj Upazila',
            'Badalgachhi Upazila',
            'Badarganj Upazila',
            'Bagatipara Upazila',
            'Bagerhat Sadar Upazila',
            'Bagha Upazila',
            'Baghaichhari Upazila',
            'Bagharpara Upazila',
            'Bagmara Upazila',
            'Bahubal Upazila',
            'Bajitpur Upazila',
            'Bakerganj Upazila',
            'Bakshiganj Upazila',
            'Balaganj Upazila',
            'Baliadangi Upazila',
            'Baliakandi Upazila',
            'Bamna Upazila',
            'Banaripara Upazila',
            'Bancharampur Upazila',
            'Bandar Upazila',
            'Bandarban Sadar Upazila',
            'Baniachong Upazila',
            'Banshkhali Upazila',
            'Baraigram Upazila',
            'Baralekha Upazila',
            'Barguna Sadar Upazila',
            'Barhatta Upazila',
            'Barisal Sadar Upazila',
            'Barkal Upazila',
            'Barura Upazila',
            'Basail Upazila',
            'Batiaghata Upazila',
            'Bauphal Upazila',
            'Beanibazar Upazila',
            'Begumganj Upazila',
            'Belabo Upazila',
            'Belkuchi Upazila',
            'Bera Upazila',
            'Betagi Upazila',
            'Bhairab Upazila',
            'Bhaluka Upazila',
            'Bhandaria Upazila',
            'Bhanga Upazila',
            'Bhangura Upazila',
            'Bhedarganj Upazila',
            'Bheramara Upazila',
            'Bhola Sadar Upazila',
            'Bholahat Upazila',
            'Bhuiyanpur Upazila',
            'Bhulli Upazila',
            'Bhurungamari Upazila',
            'Bijoynagar Upazila',
            'Bilaichhari Upazila',
            'Biral Upazila',
            'Birampur Upazila',
            'Birganj Upazila',
            'Bishwambharpur Upazila',
            'Bishwanath Upazila',
            'Boalkhali Upazila',
            'Boalmari Upazila',
            'Bochaganj Upazila',
            'Boda Upazila',
            'Bogra Sadar Upazila',
            'Borhanuddin Upazila',
            'Brahmanbaria Sadar Upazila',
            'Brahmanpara Upazila',
            'Burichang Upazila',
            'Chagalnaiya Upazila',
            'Chakaria Upazila',
            'Chandanaish Upazila',
            'Chandina Upazila',
            'Chandpur Sadar Upazila',
            'Chandraganj Upazila',
            'Chapainawabganj Sadar Upazila',
            'Char Fashion Upazila',
            'Char Rajibpur Upazila',
            'Charbhadrasan Upazila',
            'Charghat Upazila',
            'Chatkhil Upazila',
            'Chatmohar Upazila',
            'Chauddagram Upazila',
            'Chaugachha Upazila',
            'Chauhali Upazila',
            'Chhatak Upazila',
            'Chilmari Upazila',
            'Chirirbandar Upazila',
            'Chitalmari Upazila',
            'Chuadanga Sadar Upazila',
            'Chunarughat Upazila',
            'Companiganj Upazila',
            'Companiganj Upazila',
            'Cox\'s Bazar Sadar Upazila',
            'Daganbhuiyan Upazila',
            'Dakop Upazila',
            'Damudya Upazila',
            'Damurhuda Upazila',
            'Dasar Upazila',
            'Dashmina Upazila',
            'Daudkandi Upazila',
            'Daulatkhan Upazila',
            'Daulatpur Upazila',
            'Daulatpur Upazila',
            'Debhata Upazila',
            'Debidwar Upazila',
            'Debiganj Upazila',
            'Delduar Upazila',
            'Dewanganj Upazila',
            'Dhamairhat Upazila',
            'Dhamrai Upazila',
            'Dhanbari Upazila',
            'Dharmapasha Upazila',
            'Dhobaura Upazila',
            'Dhunat Upazila',
            'Dighinala Upazila',
            'Dighlia Upazila',
            'Dimla Upazila',
            'Dinajpur Sadar Upazila',
            'Dirai Upazila',
            'Doarabazar Upazila',
            'Dohar Upazila',
            'Domar Upazila',
            'Dumki Upazila',
            'Dumuria Upazila',
            'Dupchachiya Upazila',
            'Durgapur Upazila',
            'Durgapur Upazila',
            'Eidgaon Upazila',
            'Fakirhat Upazila',
            'Faridganj Upazila',
            'Faridpur Sadar Upazila',
            'Faridpur Upazila',
            'Fatikchhari Upazila',
            'Fenchuganj Upazila',
            'Feni Sadar Upazila',
            'Fulbaria Upazila',
            'Fulchhari Upazila',
            'Fulgazi Upazila',
            'Fultala Upazila',
            'Gabtoli Upazila',
            'Gafargaon Upazila',
            'Gaibandha Sadar Upazila',
            'Galachipa Upazila',
            'Gangachara Upazila',
            'Gangni Upazila',
            'Gazaria Upazila',
            'Gazipur Sadar Upazila',
            'Ghatail Upazila',
            'Ghior Upazila',
            'Ghoraghat Upazila',
            'Goalanda Upazila',
            'Gobindaganj Upazila',
            'Godagari Upazila',
            'Golapganj Upazila',
            'Gomastapur Upazila',
            'Gopalganj Sadar Upazila',
            'Gopalpur Upazila',
            'Gosairhat Upazila',
            'Gouranadi Upazila',
            'Gouripur Upazila',
            'Gowainghat Upazila',
            'Guimara Upazila',
            'Gurdaspur Upazila',
            'Habiganj Sadar Upazila',
            'Haimchar Upazila',
            'Hajiganj Upazila',
            'Hakimpur Upazila',
            'Haluaghat Upazila',
            'Harinakundu Upazila',
            'Haripur Upazila',
            'Harirampur Upazila',
            'Hathazari Upazila',
            'Hatia Upazila',
            'Hatibandha Upazila',
            'Hijla Upazila',
            'Homna Upazila',
            'Hossainpur Upazila',
            'Ishwardi Upazila',
            'Ishwarganj Upazila',
            'Islampur Upazila',
            'Itna Upazila',
            'Jagannathpur Upazila',
            'Jaintapur Upazila',
            'Jajira Upazila',
            'Jaldhaka Upazila',
            'Jamalganj Upazila',
            'Jamalpur Sadar Upazila',
            'Jessore Sadar Upazila',
            'Jhalokati Sadar Upazila',
            'Jhenaidah Sadar Upazila',
            'Jhenaigati Upazila',
            'Jhikargachha Upazila',
            'Jibannagar Upazila',
            'Jiyanagar Upazila',
            'Joypurhat Sadar Upazila',
            'Jurachari Upazila',
            'Juri Upazila',
            'Kabirhat Upazila',
            'Kachua Upazila',
            'Kachua Upazila',
            'Kahalu Upazila',
            'Kaharol Upazila',
            'Kalai Upazila',
            'Kalapara Upazila',
            'Kalaroa Upazila',
            'Kalia Upazila',
            'Kaliakair Upazila',
            'Kaliganj Upazila',
            'Kaliganj Upazila',
            'Kaliganj Upazila',
            'Kaliganj Upazila',
            'Kalihati Upazila',
            'Kalkini Upazila',
            'Kalmakanda Upazila',
            'Kalukhali Upazila',
            'Kamalganj Upazila',
            'Kamalnagar Upazila',
            'Kamarkhand Upazila',
            'Kanaighat Upazila',
            'Kapasia Upazila',
            'Kaptai Upazila',
            'Karimganj Upazila',
            'Karnaphuli Upazila',
            'Kasba Upazila',
            'Kashiani Upazila',
            'Kathalia Upazila',
            'Katiadi Upazila',
            'Kaukhali Upazila',
            'Kaukhali Upazila',
            'Kaunia Upazila',
            'Kazipur Upazila',
            'Kendua Upazila',
            'Keraniganj Upazila',
            'Keshabpur Upazila',
            'Khagrachhari Sadar Upazila',
            'Khaliajuri Upazila',
            'Khansama Upazila',
            'Khetlal Upazila',
            'Khoksa Upazila',
            'Kishoreganj Sadar Upazila',
            'Kishoreganj Upazila',
            'Kotalipara Upazila',
            'Kotchandpur Upazila',
            'Koyra Upazila',
            'Kulaura Upazila',
            'Kuliarchar Upazila',
            'Kumarkhali Upazila',
            'Kurigram Sadar Upazila',
            'Kushtia Sadar Upazila',
            'Kutubdia Upazila',
            'Lakhai Upazila',
            'Laksam Upazila',
            'Lakshmichari Upazila',
            'Lakshmipur Sadar Upazila',
            'Lalmai Upazila',
            'Lalmohan Upazila',
            'Lalmonirhat Sadar Upazila',
            'Lalpur Upazila',
            'Lama Upazila',
            'Langadu Upazila',
            'Lauhajang Upazila',
            'Lohagara Upazila',
            'Lohagara Upazila',
            'Madan Upazila',
            'Madarganj Upazila',
            'Madaripur Sadar Upazila',
            'Madhabpur Upazila',
            'Madhukhali Upazila',
            'Madhupur Upazila',
            'Madhyanagar Upazila',
            'Magura Sadar Upazila',
            'Mahadevpur Upazila',
            'Mahalchhari Upazila',
            'Maheshkhali Upazila',
            'Maheshpur Upazila',
            'Manda Upazila',
            'Manikchhari Upazila',
            'Manikganj Sadar Upazila',
            'Manirampur Upazila',
            'Manoharganj Upazila',
            'Mathbaria Upazila',
            'Matiranga Upazila',
            'Meghna Upazila',
            'Mehendiganj Upazila',
            'Meherpur Sadar Upazila',
            'Melandaha Upazila',
            'Mirpur Upazila',
            'Mirsarai Upazila',
            'Mirzaganj Upazila',
            'Mirzapur Upazila',
            'Mithamain Upazila',
            'Mithapukur Upazila',
            'Mohammadpur Upazila',
            'Mohanganj Upazila',
            'Mohanpur Upazila',
            'Mokamtala Upazila',
            'Mollahat Upazila',
            'Mongla Upazila',
            'Monohardi Upazila',
            'Monpura Upazila',
            'Morelganj Upazila',
            'Moulvibazar Sadar Upazila',
            'Mujibnagar Upazila',
            'Muksudpur Upazila',
            'Muktagachha Upazila',
            'Muladi Upazila',
            'Munshiganj Sadar Upazila',
            'Muradnagar Upazila',
            'Mymensingh Sadar Upazila',
            'Nabiganj Upazila',
            'Nabinagar Upazila',
            'Nachol Upazila',
            'Nagarkanda Upazila',
            'Nagarpur Upazila',
            'Nageshwari Upazila',
            'Naikyangchhari Upazila',
            'Nakla Upazila',
            'Nalchiti Upazila',
            'Naldanga Upazila',
            'Nalitabari Upazila',
            'Nandail Upazila',
            'Nandigram Upazila',
            'Nangalkot Upazila',
            'Naniarchar Upazila',
            'Naogaon Sadar Upazila',
            'Narail Sadar Upazila',
            'Narayanganj Sadar Upazila',
            'Naria Upazila',
            'Narsingdi Sadar',
            'Nasirnagar Upazila',
            'Natore Sadar Upazila',
            'Nawabganj Upazila',
            'Nawabganj Upazila, Dhaka',
            'Nazirpur Upazila',
            'Nesarabad Upazila',
            'Netrakona Sadar Upazila',
            'Niamatpur Upazila',
            'Nikli Upazila',
            'Nilphamari Sadar Upazila',
            'Noakhali Sadar',
            'Osmani Nagar Upazila',
            'Paba Upazila',
            'Pabna Sadar Upazila',
            'Paikgachha Upazila',
            'Pakundia Upazila',
            'Palash Upazila',
            'Palashbari Upazila',
            'Panchagarh Sadar',
            'Panchbibi Upazila',
            'Panchhari Upazila',
            'Pangsha Upazila',
            'Parashuram Upazila',
            'Parbatipur Upazila',
            'Patgram Upazila',
            'Patharghata Upazila',
            'Patiya Upazila',
            'Patnitala Upazila',
            'Patuakhali Sadar Upazila',
            'Pekua Upazila',
            'Phulbari Upazila',
            'Phulbari Upazila',
            'Phulpur Upazila',
            'Pirgachha Upazila',
            'Pirganj Upazila',
            'Pirganj Upazila',
            'Pirojpur Sadar Upazila',
            'Porsha Upazila',
            'Purbadhala Upazila',
            'Puthia Upazila',
            'Raiganj Upazila',
            'Raipur Upazila',
            'Raipura Upazila',
            'Rajapur Upazila',
            'Rajarhat Upazila',
            'Rajasthali Upazila',
            'Rajbari Sadar Upazila',
            'Rajnagar Upazila',
            'Rajoir Upazila',
            'Ramganj Upazila',
            'Ramgarh Upazila',
            'Ramgati Upazila',
            'Rampal Upazila',
            'Ramu Upazila',
            'Rangabali Upazila',
            'Rangamati Sadar Upazila',
            'Rangpur Sadar Upazila',
            'Rangunia Upazila',
            'Raninagar Upazila',
            'Ranishankail Upazila',
            'Raozan Upazila',
            'Roumari Upazila',
            'Rowangchhari Upazila',
            'Ruhia Upazila',
            'Ruma Upazila',
            'Rupganj Upazila',
            'Rupsa Upazila',
            'Sadar South Upazila',
            'Sadarpur Upazila',
            'Sadullapur Upazila',
            'Saghata Upazila',
            'Saidpur Upazila',
            'Sakhipur Upazila',
            'Saltha Upazila',
            'Sandwip Upazila',
            'Santhia Upazila',
            'Sapahar Upazila',
            'Sarail Upazila',
            'Sariakandi Upazila',
            'Sarishabari Upazila',
            'Satkania Upazila',
            'Satkhira Sadar Upazila',
            'Saturia Upazila',
            'Savar Upazila',
            'Senbag Upazila',
            'Shahjadpur Upazila',
            'Shahrasti Upazila',
            'Shailkupa Upazila',
            'Shajahanpur Upazila',
            'Shalikha Upazila',
            'Shalla Upazila',
            'Shantiganj Upazila',
            'Sharankhola Upazila',
            'Shariatpur Sadar Upazila',
            'Sharsha Upazila',
            'Shayestaganj Upazila',
            'Shayestaganj Upazila',
            'Sherpur Sadar Upazila',
            'Sherpur Upazila, Bogra',
            'Shibchar Upazila',
            'Shibganj Upazila',
            'Shibganj Upazila',
            'Shibpur Upazila',
            'Shivaloy Upazila',
            'Shyamnagar Upazila',
            'Singair Upazila',
            'Singra Upazila',
            'Sirajdikhan Upazila',
            'Sirajganj Sadar',
            'Sitakunda Upazila',
            'Sonagazi Upazila',
            'Sonaimuri Upazila',
            'Sonargaon Upazila',
            'Sonatala Upazila',
            'South Surma Upazila',
            'Sreepur Upazila',
            'Sreepur Upazila',
            'Sribardi Upazila',
            'Srimangal Upazila',
            'Srinagar Upazila',
            'Subarnachar Upazila',
            'Sujanagar Upazila',
            'Sunamganj Sadar Upazila',
            'Sundarganj Upazila',
            'Sylhet Sadar Upazila',
            'Tahirpur Upazila',
            'Tajumuddin Upazila',
            'Tala Upazila',
            'Taltoli Upazila',
            'Tangail Sadar Upazila',
            'Tanor Upazila',
            'Taraganj Upazila',
            'Tarail Upazila',
            'Tarakanda Upazila',
            'Tarash Upazila',
            'Teknaf Upazila',
            'Tentulia Upazila',
            'Terkhada Upazila',
            'Thakurgaon Sadar Upazila',
            'Thanchi Upazila',
            'The answer is',
            'Titas Upazila',
            'Tongibari Upazila',
            'Trishal Upazila',
            'Tungipara Upazila',
            'Ujirpur Upazila',
            'Ukhia Upazila',
            'Ulipur Upazila',
            'Ullapara Upazila',
            'Upazila Matlab South, Chandpur',
            'Zakiganj Upazila',
        ];

        $now = now();
        DB::table('procurement_upazilas')->insert(
            collect($upazilas)->map(fn ($name) => [
                'name' => $name,
                'created_at' => $now,
                'updated_at' => $now,
            ])->all()
        );
    }

    public function down(): void
    {
        Schema::dropIfExists('procurement_upazilas');
    }
};
